version: "3.9"

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: authdb
      POSTGRES_USER: authuser
      POSTGRES_PASSWORD: supersecret
    volumes: [ "pgdata:/var/lib/postgresql/data" ]
    networks: [ auth-net ]

  auth:
    build: .
    command: uvicorn auth_server.main:app --host 0.0.0.0 --port 8000
    env_file: .env
    volumes: [ ".:/code" ]
    depends_on: [ db ]
    ports: [ "8000:8000" ]
    networks: [ auth-net ]

volumes:
  pgdata:

networks:
  auth-net:
